# coredns_values.yaml
replicaCount: 1

service:
  type: ClusterIP
  port: 53
  targetPort: 53

# Add required labels
podLabels:
  k8s-app: kube-dns

# Ensure the selector matches the labels
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
affinity: {}
nodeSelector: {}
tolerations: []

extraArgs: []
extraEnvs: []
resources: {}

# Ensure metadata labels are set
metadata:
  labels:
    k8s-app: kube-dns