# coredns_values.yaml
replicaCount: 1

service:
  type: ClusterIP
  port: 53
  targetPort: 53

# Add required labels
podLabels:
  k8s-app: kube-dns

metadata:
  labels:
    k8s-app: kube-dns

# Ensure the selector matches the labels
selector:
  matchLabels:
    k8s-app: kube-dns

# To support legacy deployments using CoreDNS with the "k8s-app: kube-dns" label selectors
k8sAppLabelOverride: "kube-dns"