# ansible/argo_playbook.yml
- hosts: local
  become: yes
  vars_files:
    - config.yml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Create the argocd namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd

    - name: Install Argo CD
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: argocd-server
            namespace: argocd
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: argocd-server
            template:
              metadata:
                labels:
                  app: argocd-server
              spec:
                containers:
                  - name: argocd-server
                    image: argoproj/argocd:latest
                    ports:
                      - containerPort: 8080

    - name: Wait for Argo CD pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: argocd
        label_selectors:
          - app=argocd-server
      register: result
      until: result.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
      retries: 5
      delay: 30

    - name: Forward the Argo CD server port
      ansible.builtin.shell:
        cmd: "nohup kubectl port-forward svc/argocd-server -n argocd 8080:443 > /dev/null 2>&1 &"

    - name: Get initial Argo CD admin password
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: argocd
        name: argocd-initial-admin-secret
      register: argocd_secret

    - name: Decode initial admin password
      set_fact:
        argocd_password: "{{ argocd_secret.resources[0].data.password | b64decode }}"

    - name: Display initial Argo CD admin password
      debug:
        msg: "Initial Argo CD admin password: {{ argocd_password }}"