---
- name: Install ArgoCD on K3s
  hosts: all
  become: yes
  tasks:

    - name: Download kubectl binary
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      register: download_kubectl
      changed_when: download_kubectl is changed

    - name: Verify kubectl installation
      ansible.builtin.command: kubectl version --client
      register: kubectl_version
      changed_when: False

    - name: Create ArgoCD namespace
      ansible.builtin.command: kubectl create namespace argocd
      register: argocd_namespace
      ignore_errors: true
      changed_when: "'namespace/argocd created' in argocd_namespace.stdout"

    - name: Apply ArgoCD manifest
      ansible.builtin.command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      register: argocd_install
      changed_when: "'namespace/argocd created' in argocd_install.stdout or 'unchanged' in argocd_install.stdout"

    - name: Wait for ArgoCD server to be available
      ansible.builtin.command: kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd
      register: argocd_server_wait
      until: argocd_server_wait.rc == 0
      retries: 10
      delay: 30

    - name: Get the initial ArgoCD admin password
      ansible.builtin.command: kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 -d
      register: argocd_admin_password
      changed_when: False

    - name: Display ArgoCD initial admin password
      ansible.builtin.debug:
        msg: "The ArgoCD initial admin password is {{ argocd_admin_password.stdout }}"

    - name: Install ArgoCD CLI
      ansible.builtin.get_url:
        url: https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        dest: /usr/local/bin/argocd
        mode: '0755'
      register: download_argocd
      changed_when: download_argocd is changed

    - name: Verify ArgoCD CLI installation
      ansible.builtin.command: argocd version
      register: argocd_cli_version
      changed_when: False

    - name: Login to ArgoCD
      ansible.builtin.command: argocd login <argocd-server> --username admin --password {{ argocd_admin_password.stdout }} --insecure
      register: argocd_login
      changed_when: False
