# ansible/install_coredns.yml
- hosts: local
  become: yes
  vars_files:
    - config.yml
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Ensure Helm is installed
      command: helm version
      register: helm_installed
      failed_when: helm_installed.rc != 0
      ignore_errors: yes

    - name: Install Helm if not installed
      apt:
        name: helm
        state: present
      when: helm_installed.rc != 0

    - name: Add CoreDNS Helm repository
      command: helm repo add coredns https://coredns.github.io/helm
      register: helm_repo_added
      failed_when: helm_repo_added.rc != 0
      ignore_errors: yes

    - name: Update Helm repositories
      command: helm repo update
      when: helm_repo_added.rc == 0

    - name: Check if CoreDNS ConfigMap exists
      command: kubectl get configmap coredns -n kube-system
      register: coredns_configmap
      ignore_errors: yes

    - name: Patch existing CoreDNS ConfigMap if it exists
      command: >
        kubectl patch configmap coredns -n kube-system
        --type=json
        -p='[{"op": "add", "path": "/metadata/labels/app.kubernetes.io~1managed-by", "value": "Helm"},
             {"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-name", "value": "coredns"},
             {"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "kube-system"}]'
      when: coredns_configmap.rc == 0

    - name: Check if CoreDNS Deployment exists
      command: kubectl get deployment coredns -n kube-system
      register: coredns_deployment
      ignore_errors: yes

    - name: Delete existing CoreDNS Deployment if it exists
      command: kubectl delete deployment coredns -n kube-system
      when: coredns_deployment.rc == 0

    - name: Install or upgrade CoreDNS
      command: helm upgrade --install coredns coredns/coredns --namespace kube-system --create-namespace

    - name: Patch CoreDNS deployment to add required labels
      command: >
        kubectl patch deployment coredns -n kube-system
        --type=json
        -p='[{"op": "add", "path": "/spec/selector/matchLabels/k8s-app", "value": "kube-dns"},
             {"op": "add", "path": "/spec/template/metadata/labels/k8s-app", "value": "kube-dns"}]'

    - name: Verify CoreDNS deployment
      command: kubectl get deployment coredns -n kube-system --show-labels
      register: coredns_deployment_status

    - name: Display CoreDNS deployment status
      debug:
        msg: "{{ coredns_deployment_status.stdout }}"

    - name: Verify CoreDNS pods
      command: kubectl get pods -n kube-system -l k8s-app=kube-dns
      register: coredns_pods_status

    - name: Display CoreDNS pods status
      debug:
        msg: "{{ coredns_pods_status.stdout }}"
