# ansible/docker.yml
- hosts: local
  become: yes
  vars_files:
    - config.yml
  tasks:
    - name: Ensure curl is installed
      apt:
        name: curl
        state: present

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present

    - name: Create directory for Docker keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Detect Debian release
      command: cat /etc/os-release
      register: os_release

    - name: Extract Debian release version
      set_fact:
        debian_codename: "{{ item.split('=')[-1] }}"
      with_items: "{{ os_release.stdout_lines }}"
      when: item.startswith('VERSION_CODENAME=')

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ debian_codename }} stable"
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present