# ansible/docker.yml
- hosts: local
  become: yes
  vars_files:
    - config.yml
  tasks:
    - name: Ensure needed packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: De-armoring Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Gather Ubuntu release codename
      command: lsb_release -cs
      register: ubuntu_codename

    - name: Define fallback codenames
      set_fact:
        docker_codenames:
          - "{{ ubuntu_codename.stdout }}"
          - mantic      # Fallback #1
          - jammy       # Fallback #2

    - name: Attempt to add Docker apt repository with fallback
      block:
        - name: Add Docker apt repository
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ item }} stable"
            state: present
            update_cache: yes
          register: docker_repo

        - name: Debug success
          debug:
            msg: "Successfully added Docker repo using codename '{{ item }}'"

        - name: Mark success so we skip subsequent codenames
          set_fact:
            docker_repo_added: true

      rescue:
        - name: Debug failure
          debug:
            msg: "Failed with codename '{{ item }}'; trying next fallback"

      loop: "{{ docker_codenames }}"
      loop_control:
        label: "{{ item }}"
      when: not docker_repo_added | default(false)
      ignore_errors: true

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes
        state: present
