# ansible/docker.yml
- hosts: local
  become: yes
  vars_files:
    - config.yml
  tasks:
    - name: Ensure needed packages are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: De-armoring Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Gather Ubuntu release codename
      command: lsb_release -cs
      register: ubuntu_codename

    - name: Attempt to add Docker apt repository for current distro
      block:
          - name: Add Docker apt repository
            apt_repository:
              repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
              state: present
              update_cache: yes
      rescue:
        - name: Use jammy as fallback
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
            state: present
            update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: yes
        state: present

    - name: Add the current user to the docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Create /etc/docker directory if it doesn't exist
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure Docker logging defaults
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
        owner: root
        group: root
        mode: '0644'

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
        daemon_reload: yes
