apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-config-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  nodePath: "/mnt/nas/k8sconfig"
