- name: Ensure patch script exists and is executable
  hosts: local
  become: yes
  tasks:
    - name: Copy local-path patch JSON
      copy:
        src: files/local-path-patch.json
        dest: /usr/local/share/local-path-patch.json
        mode: '0644'
        owner: root
        group: root
    - name: Copy local-path-config patch script from template
      copy:
        src: files/k3s-local-path-fix.sh
        dest: /usr/local/bin/k3s-local-path-fix.sh
        mode: '0755'
        owner: root
        group: root

    - name: Install systemd unit for patch script
      copy:
        dest: /etc/systemd/system/k3s-local-path-fix.service
        mode: '0644'
        owner: root
        group: root
        content: |
          [Unit]
          Description=Patch local-path-config to support NAS PVCs
          After=network-online.target k3s.service
          Wants=network-online.target

          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/k3s-local-path-fix.sh
          RemainAfterExit=yes

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start patch service
      systemd:
        name: k3s-local-path-fix.service
        enabled: yes
        state: started
