---
- name: Manage systemd-resolved and configure DNS
  hosts: local
  become: yes
  tasks:
    - name: Stop systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Backup existing resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        backup: yes
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

    - name: Create new resolv.conf with Google DNS
      copy:
        content: |
          nameserver 8.8.8.8
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644'
      when: ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'

    - name: Backup traefik.yaml
      copy:
        src: /var/lib/rancher/k3s/server/manifests/traefik.yaml
        dest: /var/lib/rancher/k3s/server/manifests/traefik.yaml.backup
        remote_src: yes
      ignore_errors: yes

    - name: Remove traefik.yaml
      file:
        path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
        state: absent

    - name: Restart K3s service
      systemd:
        name: k3s
        state: restarted