apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: retain-default-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: Immediate
